### ISSUE TITLE
Exception thrown by DateTimePicker when setValue(null) is called

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-date-time-picker-flow#60]
This is a reopen of https://github.com/vaadin/vaadin-date-time-picker-flow/issues/33

Under Vaadin 14.3.2, the same issue reappears and can be reproduced easily with the same example app:

```java
@Route("date-time-picker")
public class DateTimePickerView extends Div {

	public DateTimePickerView() {
		DateTimePicker contr = new DateTimePicker();
		add(contr);
		contr.setValue(LocalDateTime.now());
	}

}
```

Stacktrace

```
java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at java.time.LocalDateTime.parse(LocalDateTime.java:477)
	at com.vaadin.flow.component.datetimepicker.DateTimePicker.lambda$setValue$157cfcf3$1(DateTimePicker.java:250)
```

**Comment by tomivirkki** [comment]
Backported and released as [1.1.1](https://github.com/vaadin/vaadin-date-time-picker-flow/releases/tag/1.1.1)
Waiting to get merged to platform in https://github.com/vaadin/platform/pull/1483/files#diff-1b1ba5594d5bdffa6ee955bbfcfd2702R148
